### ISSUE TITLE
It will occupy the space to force GitHub main body left shift

### ISSUE THREAD

**Issue by Honghe** [otariidae/github-markdown-toc#6]
The following 2 pics show the GitHub main body shifting left after showing toc, though there is still space in the browser 

* hide toc
![image](https://user-images.githubusercontent.com/1092722/40421282-f19592d0-5ebd-11e8-8bb4-c5d9a0404a5a.png)

* show toc
![image](https://user-images.githubusercontent.com/1092722/40421274-e903418a-5ebd-11e8-9e81-7d320806b0d9.png)

**Comment by otariidae** [comment]
Sorry for the late reply.
Thank you for using this extension.

You seem to use Octotree.
Now this extension conflicts with Octotree.
Octotree overlays on the space applying many styles to the page, and GitHub Markdown Toc is on the right side of the page turning the page width narrow.
This appears if you use a display whose width is over 1481 px.

Now I  have no plan for changing ToC's behavior.

![Ototree and ToC](https://user-images.githubusercontent.com/20238714/40874195-55f5e5d6-66a7-11e8-984b-ecf94edc848f.png)

**Comment by Honghe** [comment]
It works fine on Ubuntu 16.04, but unusually on Windows 10. Both Chrome v66 and 1600x900.

**Comment by otariidae** [comment]
I can reproduce this issue on Chrome v67 on both Ubuntu 16.04 and Windows 10.
It is strange...

If I change the current implementation, code will be complicated.
I prefer simple way.
Anyone knows simple implementation that has less side effects on GitHub content and other extensions?

This is not only this extension's problem.
I close this issue now. If someone finds good idea, I will reopen.
I am sorry for the inconvenience.
